name: Deploy latest pages

on: 
  push:
    branches:
      - raw

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and Deploy
      uses: grasilife/github-pages-deploy-action@v1.2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: raw
        BRANCH: master
        FOLDER: docs/.vuepress/dist
